### ISSUE TITLE
Scrolling need fix on latest Chrome version

### ISSUE THREAD

**Issue by sdhal** [srizon/Drifolio-Bootstrap#2]
Hi, I found scrolling not working anymore after my chrome got upgraded to latest version (43).

I am trying find the cause but meanwhile thought to let you know as well.

**Comment by sdhal** [comment]
Removing jquery.nicescroll, fixes the issue for me.

**Comment by srizon** [comment]
Hi, thanks for reporting the issue. It's resolved now.

Just updated with the Latest version of Nicescroll 3.6.0. 
You can just replace your **jquery.nicescroll.min.js** file with [this one.](https://github.com/srizon/Drifolio-Bootstrap/blob/ea23d11ae6e1346e87cdf31b47b319c4ee30f5da/js/jquery.nicescroll.min.js)

That will be all.
